<a href="https://colab.research.google.com/github/rameshwargupta/THL_RUN/blob/master/pytorch_tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import torch
print (torch.__version__)

2.6.0+cu124


checking gpu

In [23]:

print ("gpu is avialbale") #togo runtime option to chnage cpu or gpu
print (torch.cuda.get_device_name)
print (torch.cuda.get_device_capability)
print(torch.cuda.device_count)
print (torch.cuda.temperature)

print (torch.cuda.get_device_name)

gpu is avialbale
<function get_device_name at 0x7d07487b1b20>
<function get_device_capability at 0x7d07487b1bc0>
<function device_count at 0x7d07487b2700>
<function temperature at 0x7d07487b3560>
<function get_device_name at 0x7d07487b1b20>


creating a tensor

In [8]:
torch.empty(2,3)

tensor([[-1.8942e-30,  4.4851e-41,  2.6925e-08],
        [ 0.0000e+00,  1.4574e-43,  6.4460e-44]])

In [16]:
a = torch.zeros(2,3)
b = torch.ones(2,3)
c = torch.rand(2,3)
torch.manual_seed(100)
d = torch.rand(2,3)
print (a,b,c,d)


tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]]) tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
torch.tensor([1,2,3],[1,2,3])

In [29]:
print (torch.linspace(0,10,5)) #zero to 10 in 5 random steps evenlly spaced
print(torch.arange(0,5))  #zero to 5 creating a tensor
print (type(torch.arange(0,3)))

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([0, 1, 2, 3, 4])
<class 'torch.Tensor'>


In [35]:
print(torch.eye(5)) #return identity matrix
print(torch.eye(3))
print (torch.eye(1,3))
print (torch.full((3,3),5))
print (torch.full((2,2),5))
print (torch.full((3,2),1))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
tensor([[5, 5],
        [5, 5]])
tensor([[1, 1],
        [1, 1],
        [1, 1]])


tensor shape

In [36]:
x = torch.tensor([[1,2],[2,2]])
print (x.shape)

torch.Size([2, 2])


creating similar tensor

In [51]:
x = torch.tensor([[1,2],[2,2]])
p = torch.empty_like(x)
print (p)
print (torch.zeros_like(x))
print (torch.ones_like(x))
print (torch.rand_like(x,dtype=torch.float))

tensor([[       10791152, 137466723030848],
        [137466723030800, 137471395269680]])
tensor([[0, 0],
        [0, 0]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])


tensor data type

In [50]:
print(x.dtype)
print(torch.tensor([1.0,2.0,3],dtype=torch.int64))
print(torch.tensor([1.0,2.0,3],dtype=torch.float32))
print(x.to(torch.float32))

torch.int64
tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([[1., 2.],
        [2., 2.]])


mathmetical operation

In [55]:
x = torch.rand(2,2)
y = torch.ones(2,2)
print (x,y)
print (y+2)
print (y-1)
print(y*3)
print(y/2)
print(y**2)

tensor([[0.5557, 0.9770],
        [0.4440, 0.9478]]) tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [74]:
a = torch.full((2,2),2)
b = torch.full((2,2),4)
print (a,b)
print (a+b)
print (a-b)
print (a*b)
print (a/b)

c = torch.tensor([1,-2,.3,-5])
print (torch.abs(c))
print (torch.neg(c))
print (torch.round(c))
print (torch.ceil(c))
print (torch.floor(c))
print (torch.clamp(c, min = 0,max = 2))# keeping in a specified range



tensor([[2, 2],
        [2, 2]]) tensor([[4, 4],
        [4, 4]])
tensor([[6, 6],
        [6, 6]])
tensor([[-2, -2],
        [-2, -2]])
tensor([[8, 8],
        [8, 8]])
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
tensor([1.0000, 2.0000, 0.3000, 5.0000])
tensor([-1.0000,  2.0000, -0.3000,  5.0000])
tensor([ 1., -2.,  0., -5.])
tensor([ 1., -2.,  1., -5.])
tensor([ 1., -2.,  0., -5.])
tensor([1.0000, 0.0000, 0.3000, 0.0000])


reductin method


In [77]:
c = torch.tensor([1,2,3,5],dtype=float)
print (torch.sum(a))
print (torch.sum(b))
print (torch.sum(a,dim = 0)) #sum according to axis
print(torch.sum(a,dim = 1))
print(torch.mean(c))
print(torch.mean(c,dim = 0)) #means based on column
print(torch.median(a))
print(torch.max(c))
print(torch.min(c))
print (torch.prod(a))
print (torch.std(c))
a = torch.full((2,2),2)
b = torch.full((2,2),4)
print (torch.var(c))
print (torch.argmax(c))
print (torch.argmin(c))

tensor(8)
tensor(16)
tensor([4, 4])
tensor([4, 4])
tensor(2.7500, dtype=torch.float64)
tensor(2.7500, dtype=torch.float64)
tensor(2)
tensor(5., dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(16)
tensor(1.7078, dtype=torch.float64)
tensor(2.9167, dtype=torch.float64)
tensor(3)
tensor(0)


In [ ]:
trix operations

In [87]:
a = torch.full((2,2),2)
b = torch.full((2,2),4)
print (torch.matmul(a,b))
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
print (vector1,vector2)
print (torch.dot(vector1,vector2))
print (torch.matmul(vector1,vector2))


############transpose
h = torch.randint(size =(4,4),low = 0,high = 10,dtype =float)
print (h)
print (torch.transpose(h,0,1))
print (torch.det(h))

tensor([[16, 16],
        [16, 16]])
tensor([1, 2]) tensor([3, 4])
tensor(11)
tensor(11)
tensor([[8., 4., 7., 2.],
        [3., 8., 5., 6.],
        [2., 9., 5., 0.],
        [4., 2., 7., 1.]], dtype=torch.float64)
tensor([[8., 3., 2., 4.],
        [4., 8., 9., 2.],
        [7., 5., 5., 7.],
        [2., 6., 0., 1.]], dtype=torch.float64)
tensor(1267., dtype=torch.float64)


comparison operation

In [94]:
h = torch.randint(size =(4,4),low = 0,high = 10,dtype =float)
f = torch.randint(size =(4,4),low = 0,high = 10,dtype =float)
print (h)
print (f)
print (f>h)
print (f==h)
print (f!=h)

print (torch.log(h))
print (torch.exp(h))
print (torch.sqrt(h))
print (torch.sigmoid(h))
print (torch.softmax(h,dim = 0))
print (torch.relu(h))

tensor([[0., 3., 3., 4.],
        [8., 8., 1., 2.],
        [4., 9., 4., 0.],
        [9., 7., 5., 0.]], dtype=torch.float64)
tensor([[6., 7., 7., 8.],
        [8., 9., 6., 2.],
        [9., 4., 5., 5.],
        [3., 5., 0., 7.]], dtype=torch.float64)
tensor([[ True,  True,  True,  True],
        [False,  True,  True, False],
        [ True, False,  True,  True],
        [False, False, False,  True]])
tensor([[False, False, False, False],
        [ True, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[ True,  True,  True,  True],
        [False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([[  -inf, 1.0986, 1.0986, 1.3863],
        [2.0794, 2.0794, 0.0000, 0.6931],
        [1.3863, 2.1972, 1.3863,   -inf],
        [2.1972, 1.9459, 1.6094,   -inf]], dtype=torch.float64)
tensor([[1.0000e+00, 2.0086e+01, 2.0086e+01, 5.4598e+01],
        [2.9810e+03, 2.9810e+03, 2.7183e+

inplace operation

In [97]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print (m)
print (n)

#add m+n and stroe in m
print (m.add_(n))
print (m)

#### user method_ to make inplace operations

tensor([[0.0257, 0.4205, 0.0656],
        [0.4508, 0.0553, 0.3140]])
tensor([[0.7460, 0.9357, 0.8925],
        [0.1370, 0.1803, 0.4023]])
tensor([[0.7717, 1.3562, 0.9581],
        [0.5879, 0.2357, 0.7162]])
tensor([[0.7717, 1.3562, 0.9581],
        [0.5879, 0.2357, 0.7162]])


copy tensor

In [99]:
a =torch.rand(2,3)
b=a
print (a,b)
a[0][0] = 0
print (a,b)  # this is problem as changes made in a get affected in b

c = a.clone()  # right method  check id (a) and id (b)

tensor([[0.4296, 0.3692, 0.1611],
        [0.9422, 0.8777, 0.5321]]) tensor([[0.4296, 0.3692, 0.1611],
        [0.9422, 0.8777, 0.5321]])
tensor([[0.0000, 0.3692, 0.1611],
        [0.9422, 0.8777, 0.5321]]) tensor([[0.0000, 0.3692, 0.1611],
        [0.9422, 0.8777, 0.5321]])


check gpu

In [107]:
torch.cuda.is_available()
device1 = torch.device('cuda')
torch.rand((2,2), device=device1)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

gpu vs cpu

In [109]:
import time
matrix1  =torch.randn(1000,1000)
matrix2 = torch.randn(1000,1000)
start_time = time.time()
result = torch.matmul(matrix1,matrix2)

gpu_time = time.time()-start_time
print (gpu_time)

0.06020975112915039


reshaping operations

In [121]:
a = torch.ones(4,4)
print (a.reshape(2,2,2,2))

print (a.flatten())

c = torch.rand(226,226,3)
print (c.unsqueeze(0).shape)
print (c.unsqueeze(2).shape)  #similar we have sqeeze



tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([1, 226, 226, 3])
tensor([[[[0.3900, 0.7244, 0.0455]],

         [[0.3638, 0.3444, 0.1089]],

         [[0.6645, 0.1778, 0.8992]],

         ...,

         [[0.2539, 0.2832, 0.6308]],

         [[0.6229, 0.0888, 0.0252]],

         [[0.4848, 0.9366, 0.5236]]],


        [[[0.9700, 0.9732, 0.1282]],

         [[0.8604, 0.3080, 0.2053]],

         [[0.4868, 0.1272, 0.3009]],

         ...,

         [[0.4648, 0.4217, 0.1947]],

         [[0.1844, 0.7690, 0.8243]],

         [[0.4315, 0.3121, 0.6029]]],


        [[[0.9979, 0.1081, 0.7758]],

         [[0.0354, 0.9395, 0.7149]],

         [[0.7726, 0.4131, 0.7584]],

         ...,

         [[0.4117, 0.5848, 0.0488]],

         [[0.8143, 0.4023, 0.0366]],

         [[0.3522, 0.4516, 0.870

numpy and pytorch  conversion

In [129]:
import numpy as np

a = torch.tensor([1,2,3,4])
b = a.numpy()
c = a.numpy()
print (b)
print (type(b))

print(torch.from_numpy(c))

[1 2 3 4]
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4])
